DELETE http://localhost:3001/phonebook/1

###
POST  http://localhost:3001/phonebook
Content-Type: application/json


{
    "name": "kawdsfawwk",
    "number": 2232422
}

###
GET  http://localhost:3001/phonebook